services:
  - type: web
    name: creative-states-cycling
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn creative_states.wsgi:application --log-file -
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SECURE_PROXY_SSL_HEADER
        value: "True"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: DJANGO_SESSION_COOKIE_SECURE
        value: "True"
      - key: DJANGO_CSRF_COOKIE_SECURE
        value: "True"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: DJANGO_SECURE_HSTS_PRELOAD
        value: "True"
